# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Copy file via ssh
        uses: appleboy/scp-action@master
        with:
          key: ${{secrets.SERVER_SSH_KEY}}
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          source: "*"
          target: "aksis"
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SERVER_SSH_KEY}}
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          script: |
            pm2 delete front
            cd aksis

            rm -r .next
            rm .env.local
            touch .env.local

            echo NEXT_PUBLIC_API_URL=/api >> .env.local
            echo NEXT_LOCAL_API_URL=https://doxdox.bitrix24.eu/rest/8/mkzqll4xdor1oxz0/ >> .env.local

            cat .env.local

            yarn
            yarn build
            yarn postbuild
            yarn start:prod
