# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Copy file via ssh
        uses: appleboy/scp-action@master
        with:
          key: ${{secrets.SERVER_SSH_KEY}}
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          source: "*"
          target: "aksis"
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SERVER_SSH_KEY}}
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          script: |
            pm2 delete front
            cd aksis

            rm -r .next
            rm .env.local
            touch .env.local

            echo NEXT_PUBLIC_API_URL=/api >> .env.local
            echo SITE_URL=https://aksis.agency >> .env.local
            echo NEXT_LOCAL_API_URL=https://aksis-agency.planfix.com/webhook/json/yfr4-eph7-kmjx-h3s0 >> .env.local

            echo CONTENTFUL_DELIVERY_API_ACCESS_TOKEN=p02vL-APevX_2yqlge0FcUuNP8zCVFXNyq_zTm8ilfM >> .env.local
            echo CONTENTFUL_MANAGEMENT_API_ACCESS_TOKEN=CFPAT-6BuVSQDbBvF0Xx78SuY0j1RP61fA2k54_GpcmIxNSXo >> .env.local
            echo CONTENTFUL_SPACE_ID=o5pzd75oy6c1 >> .env.local

            cat .env.local

            yarn
            yarn build
            yarn postbuild
            yarn start:prod
